---
# task for dgnest.asterisk

- name: unarchive package asterisk
  become: true
  unarchive: src="{{ _asterisk_url_wget }}" dest="/tmp/" remote_src=True
  when:
    - _asterisk_path is defined
  register: asterisk_src_download
