---

# task file for dgnest.asterisk

- name: Update package repositories
  sudo: yes
  apt:
    update_cache: True
  when:
    - ansible_os_family == "Debian"
  tags:
    - apt
    - update_cache

- name: Install asterisk package dependencies
  become: yes
  package:
    name: "{{ item }}"
    state: present
  register: install_asterisk_package_dependencies
  with_items: "{{ _asterisk_package_dependencies | default([]) }}"
  when:
    - _asterisk_package_dependencies is defined
  tags:
    - packages
    - dependencies
