---
# environment file for dgnest.asterisk

- name: Create files asterisk
  sudo: yes
  file:
    path: "{{ item.path }}"
    state: "{{ item.state }}"
  with_items: "{{ _asterisk_create_files | default({}) }}"
  when:
    _asterisk_create_files is defined
