---
# task for dgnest.asterisk

- include: install.d/CentOS.yaml
  when: ansible_distribution == "CentOS"
  tags:
    - asterisk

- include: install.d/Ubuntu.yaml
  when: ansible_distribution == "Ubuntu"
  tags:
    - asterisk