---

# task file for dgnest.asterisk

- name: Ensure apt cache is up to date
  apt:
    update_cache: yes


- name: Install asterisk dependencies
  apt: name={{ item }} state=present update_cache=yes
  with_items: "{{ _asterisk_packages | default([]) }}"
  when:
    - _asterisk_packages is defined
  tags:
    - asterisk
